
set(PROJECT_TOOLCHAIN_PATH "" CACHE STRING "Path to arm-none-eabi-gcc toolchain" FORCE)
set(PROJECT_ARCH_CPU "armv7e-m" CACHE STRING "ARM architecture CPU" FORCE)
set(PROJECT_ARCH_PROJECT_MODE "thumb" CACHE STRING "ARM architecture ARM mode" FORCE)
set(PROJECT_ARCH_FPU "fpv5-d16" CACHE STRING "ARM architecture FPU" FORCE)
set(PROJECT_ARCH_FLOAT_ABI "hard" CACHE STRING "ARM architecture float ABI" FORCE)
set(PROJECT_COMPILER_ABI "arm-none-eabi-" CACHE STRING "ARM compiler ABI" FORCE)
#set(PROJECT_USE_NEWLIB "TRUE" CACHE BOOL "Use newlib" FORCE)

message(STATUS "PROJECT_TOOLCHAIN_PATH: ${PROJECT_TOOLCHAIN_PATH}")
message(STATUS "PROJECT_COMPILER_ABI: ${PROJECT_COMPILER_ABI}")
message(STATUS "PROJECT_ARCH_CPU: ${PROJECT_ARCH_CPU}")
message(STATUS "PROJECT_ARCH_PROJECT_MODE: ${PROJECT_ARCH_PROJECT_MODE}")
message(STATUS "PROJECT_ARCH_FPU: ${PROJECT_ARCH_FPU}")
message(STATUS "PROJECT_ARCH_FLOAT_ABI: ${PROJECT_ARCH_FLOAT_ABI}")
message(STATUS "PROJECT_COMPILER_ABI: ${PROJECT_COMPILER_ABI}")
message(STATUS "PROJECT_USE_NEWLIB: ${PROJECT_USE_NEWLIB}")



set(PROJECT_USE_NOHOST "TRUE" CACHE BOOL "Use no host" FORCE)