set(PROJECT_TOOLCHAIN_PATH x86_64-linux-gnu-gcc CACHE PATH "Path to x86_64-linux-gnu-gcc toolchain")
set(PROJECT_ARCH_CPU "x86_64" CACHE STRING "x86-64 architecture CPU")
set(PROJECT_ARCH_ARM_MODE "none" CACHE STRING "x86-64 architecture ARM mode (not applicable)")
set(PROJECT_ARCH_FPU "" CACHE STRING "x86-64 architecture FPU (not applicable)")
set(PROJECT_ARCH_FLOAT_ABI "" CACHE STRING "x86-64 architecture float ABI (not applicable)")
set(PROJECT_COMPILER_ABI "" CACHE STRING "x86-64 compiler ABI (not applicable)")
set(PROJECT_LINKER_SCRIPT_PATH "" CACHE STRING "x86-64 linker script path (not applicable)")



message(STATUS "PROJECT_TOOLCHAIN_PATH: ${PROJECT_TOOLCHAIN_PATH}")
message(STATUS "PROJECT_ARCH_CPU: ${PROJECT_ARCH_CPU}")
message(STATUS "PROJECT_ARCH_PROJECT_MODE: ${PROJECT_ARCH_PROJECT_MODE}")
message(STATUS "PROJECT_ARCH_FPU: ${PROJECT_ARCH_FPU}")
message(STATUS "PROJECT_ARCH_FLOAT_ABI: ${PROJECT_ARCH_FLOAT_ABI}")
message(STATUS "PROJECT_COMPILER_ABI: ${PROJECT_COMPILER_ABI}")
message(STATUS "PROJECT_LINKER_SCRIPT_PATH: ${PROJECT_LINKER_SCRIPT_PATH}")